{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "FUNDiT kyc Api",
    "description" : "FUNDiT kyc",
    "contact" : {
      "email" : "richard.adebayo@fundit.com.ng"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/Fundit/KYC/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  }, {
    "url" : "https://api.fundit.com.ng",
    "description" : "FUNDiT KYC"
  } ],
  "tags" : [ {
    "name" : "Users",
    "description" : "Secured users-only calls"
  }, {
    "name" : "developers",
    "description" : "Operations available to registered Users"
  } ],
  "paths" : {
    "/kyc/customer/basic/verify" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "searches Bvn Database",
        "description" : "By passing in the appropriate options, you can search for\navailable inventory in the system\n",
        "operationId" : "search Database",
        "parameters" : [ {
          "name" : "userId",
          "in" : "query",
          "description" : "pass an userId search string to look up the partner",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "description" : "BVN data to search for",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/BvnData"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "search results from database",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BvnResponse"
                }
              }
            }
          },
          "401" : {
            "description" : "Invalid partnerId ,Create an account"
          }
        }
      }
    },
    "/kyc/customer/crc/verify" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "search for a customer credit scoring",
        "description" : "search for a customer credit scoring from our Partners",
        "operationId" : "searchScoring",
        "responses" : {
          "201" : {
            "description" : ""
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "BvnData" : {
        "required" : [ "idType", "idValue" ],
        "type" : "object",
        "properties" : {
          "idType" : {
            "$ref" : "#/components/schemas/BvnData_idType"
          },
          "idValue" : {
            "maxLength" : 11,
            "minLength" : 11,
            "type" : "string",
            "example" : "00000000000"
          }
        }
      },
      "BvnResponse" : {
        "required" : [ "_id", "bvn", "date_of_birth", "email", "first_name", "last_name", "lga_of_birth", "marital_status", "middle_name", "nationality", "phone_number_1", "photo", "residential_address", "state_of_origin", "success" ],
        "type" : "object",
        "properties" : {
          "_id" : {
            "type" : "string",
            "example" : "6534cc912b51996c07818241"
          },
          "last_name" : {
            "type" : "string",
            "example" : "Leo"
          },
          "first_name" : {
            "type" : "string",
            "example" : "Joe"
          },
          "email" : {
            "type" : "string",
            "example" : "Joe@smileidentity.com"
          },
          "bvn" : {
            "type" : "string",
            "example" : "0"
          },
          "marital_status" : {
            "type" : "string",
            "example" : "Single"
          },
          "middle_name" : {
            "type" : "string",
            "example" : "Doe"
          },
          "date_of_birth" : {
            "type" : "string",
            "example" : "2000-09-20T00:00:00.000Z"
          },
          "lga_of_origin" : {
            "type" : "string",
            "example" : "Mushin"
          },
          "nationality" : {
            "type" : "string",
            "example" : "Nigeria"
          },
          "residential_address" : {
            "type" : "string",
            "example" : "10, Workbox, Ojora Close, Victoria Island, Lagos"
          },
          "state_of_origin" : {
            "type" : "string",
            "example" : "Lagos State"
          },
          "gender" : {
            "type" : "string",
            "example" : "Male"
          },
          "lga_of_residence" : {
            "type" : "string",
            "example" : "Mushin"
          },
          "state_of_residence" : {
            "type" : "string",
            "example" : "Lagos State"
          },
          "success" : {
            "type" : "boolean",
            "example" : true
          },
          "Photo" : {
            "type" : "string",
            "format" : "url",
            "example" : "http://res.cloudinary.com/fundit-bvn/image/upload/v1697959056/bvn/bj48rfwlympbmwqond31.jpg"
          }
        }
      },
      "BvnData_idType" : {
        "type" : "object",
        "properties" : {
          "label" : {
            "type" : "string",
            "example" : "BVN"
          },
          "value" : {
            "type" : "string",
            "example" : "BVN"
          }
        }
      }
    }
  }
}